<?php

use artorganizer\Controller\{addArtigoController,
    addPastaController,
    attArtigoController,
    attPastaController,
    atualizacaoController,
    cadastroController,
    configuracaoController,
    excluirArtigoController,
    excluirPastaController,
    excluirSessaoController,
    explorarController,
    formRedefinirSenhaController,
    homeController,
    infoArtigoController,
    infoPastaController,
    landingpageController,
    loginController,
    logoutController,
    pegarIdExcluir,
    pegarSessaoController,
    pesquisaController,
    processarSolicitacaoController,
    recuperarController,
    redefinirSenhaController,
    voltarController
};

return [
    "GET|/" => landingpageController::class,
    "POST|/login" => loginController::class,
    "POST|/cadastrar" => cadastroController::class,
    "GET|/home" => homeController::class,
    "GET|/explorar" => explorarController::class,
    "POST|/pesquisa" => pesquisaController::class,
    "GET|/logout" => logoutController::class,
    "GET|/configuracao" => configuracaoController::class,
    "POST|/atualizacao" => atualizacaoController::class,
    "POST|/adicionarArtigo" => addArtigoController::class,
    "GET|/informacaoArtigo" => infoArtigoController::class,
    "POST|/atualizarArtigo" => attArtigoController::class,
    "GET|/excluirArtigo" => excluirArtigoController::class,
    "POST|/adicionarPasta" => addPastaController::class,
    "GET|/informacaoPasta" => infoPastaController::class,
    "GET|/excluirPasta" => excluirPastaController::class,
    "POST|/atualizarPasta" => attPastaController::class,
    "GET|/pegarIdExcluir" => pegarIdExcluir::class,
    "GET|/excluirSessao" => excluirSessaoController::class,
    "GET|/voltar" => voltarController::class,
    "GET|/pegarSessao" => pegarSessaoController::class,
    "GET|/recuperar" => recuperarController::class,
    "POST|/processar_solicitacao" => processarSolicitacaoController::class,
    "GET|/redefinir_senha" => formRedefinirSenhaController::class,
    "POST|/redefinir_senha" => redefinirSenhaController::class
];
